import mongoose from 'mongoose';

const aiLearningSchema = new mongoose.Schema({
  workflowId: { type: mongoose.Schema.Types.ObjectId, ref: 'Workflow', required: true },
  jobId: { type: mongoose.Schema.Types.ObjectId, ref: 'AutomationJob', required: true },
  
  targetUrl: { type: String, required: true },
  errorSignature: { type: String, required: true },
  rawLogs: [{ type: String }],
  
  // The structured insight generated by the AI
  insight: {
    rootCause: { type: String, required: true },
    suggestedFix: { type: String, required: true },
    confidence: { type: Number, required: true },
    updatedSelector: { type: String } // Optional: If the AI suggests a new CSS selector
  },
  
  status: { type: String, enum: ['PENDING_REVIEW', 'APPLIED', 'REJECTED'], default: 'PENDING_REVIEW' }
}, { timestamps: true });

export const AILearning = mongoose.model('AILearning', aiLearningSchema);
